### PR TITLE
Remove elements by key instead of index

### PR DESCRIPTION
**Pull request by hctpbl**
Hi David,

At my company, we've been using your component (thanks a lot for it!) in production for our app. In order to improve our performance we added some kind of infinite scroll to the isotope grid, adding elements when reaching the end of the scroll, and for that to work we had to stop relying on Isotope for filtering and sorting, and we directly do that on the parent component, passing a new list to isotope each time the user adds a filter to sort or changes the order.

This raised an issue in this component: The array of `displayChildren` you pass to the `createElement` function as a result of the component `render` function is, very frequently, not sorted the same way as the `this.$el.children` array of elements you can find on the `mounted` and `beforeMount` methods. This means that the indexes stored on `removedKeys` no longer point to the nodes that have to be removed, but to random elements inside `this.$el.children`. Removing wrong elements leads to the isotope component having wrong items when filtering and, ultimately, vue throwing an error when trying to render a new list, preventing the layout to be modified again until the user reloads the page.

I have fixed this by storing the list of mandatory `key` props instead of the indexes to:

1. Get the elements to pass to the isotope method `remove`
2. Remove the right elements inside the `children` array of the `vnode` of the isotope component
3. Remove the right vue instances inside the `$children` array of the isotope component.

Note that you did not clean the `$children` array before. I'm not sure it's necessary, but I find it at least more memory efficient.

Let me know if you need further explanations or want me to change anything, I may have missed a lot of cases here. Also, I did the gulp build but had to manually remove some of the generated code to adapt it to the existing one, hope that worked fine.

Cheers!

### CODE REVIEW

**Comment by hctpbl** [comment]
By the way, this PR may fix issue #46

**Comment by David-Desmaisons** [comment]
@hctpbl Thanks for your contribution.
I will need some time to review it since these are impacting changes.

**Comment by JJCLane** [comment]
Thanks @hctpbl, I've pulled in your PR into [mine](https://github.com/David-Desmaisons/Vue.Isotope/pull/57) and fixed it to allow static elements (e.g. for element sizing) and now everything works nicely!

**Comment by giraz82** [comment]
Any news about this?
Using a getter from the store with a precise sorting I got a similar issue: the elements are not sorted as the original array in the store.
Thank you.

**Pull request closed without merging**
